### ISSUE TITLE
Program Partners Page

### ISSUE THREAD

**Issue by brian-frederick** [brian-frederick/HPNC-Umbraco-Site#25] opened 2018-04-07 20:21 UTC
Top of page should feature three photo circles before header
Here we will include logos of partners, descriptions of their offerings, and links to their own pages

**Comment by brian-frederick** [comment] 2018-05-16 00:27
@vemigh 
Ability to upload logos, add descriptions, and links to pages
use staff page as template

**Comment by vemigh** [comment] 2018-08-15 23:27
duplicate of staff page

**Comment by brian-frederick** [comment] 2018-08-26 04:59
@vemigh this page can be seen at http://hpnclub.azurewebsites.net/program-partners

**Comment by vemigh** [comment] 2018-08-27 15:57
Excellent, thank you! 

One last thing: the program partners circle on the home page should link directly to this page.

**Comment by brian-frederick** [comment] 2018-08-27 20:47
@vemigh that's done! for future reference, you can configure where those circles link to.

**Comment by vemigh** [comment] 2018-08-28 14:34
Perfect, thank you!!

**Closed** 2018-09-03 15:05 UTC
Labels: Priority: 2, new page, program partners page, scope?, size: 10
